#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy=1.7.\* -y
echo "frontend web-front
        bind *:80
        default_backend abdulrazaq.tech

backend abdulrazaq.tech
        balance roundrobin
        server web1 52.207.88.132:80 check
        server web2 52.86.224.229:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
